# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Run golangci-lint with reviewdog
  # You may pin to the exact commit or the version.
  # uses: reviewdog/action-golangci-lint@3dfdce20f5ca12d264c214abb993dbb40834da90
  uses: reviewdog/action-golangci-lint@v2.7.2
  with:
    # GITHUB_TOKEN.
    github_token: # default is ${{ github.token }}
    # golangci-lint flags. (golangci-lint run --out-format=line-number <golangci_lint_flags>)
    golangci_lint_flags: # optional, default is 
    # Tool name to use for reviewdog reporter
    tool_name: # optional, default is golangci
    # Report level for reviewdog [info,warning,error]
    level: # optional, default is error
    # Reporter of reviewdog command [github-pr-check,github-pr-review,github-check].
    reporter: # optional, default is github-pr-check
    # Filtering for the reviewdog command [added,diff_context,file,nofilter].
Default is added.

    filter_mode: # optional, default is added
    # If set to `none`, always use exit code 0 for reviewdog.
Otherwise, exit code 1 for reviewdog if it finds at least 1 issue with severity greater than or equal to the given level.
Possible values: [none,any,info,warning,error]
Default is `none`.

    fail_level: # optional, default is none
    # Deprecated, use `fail_level` instead.
Exit code for reviewdog when errors are found [true,false]
Default is `false`.

    fail_on_error: # optional, default is false
    # Additional reviewdog flags
    reviewdog_flags: # optional, default is 
    # Working directory relative to the root directory.
    workdir: # optional, default is .
    # the version of reviewdog
    reviewdog_version: # optional, default is latest
    # the version of golangci-lint
    golangci_lint_version: # optional, default is latest
    # the version of Go. By default, the latest version of Go 1.x is installed.
    go_version: # optional
    # Path to the go.mod file or the file containing only Go version.
    go_version_file: # optional
    # enable cache
    cache: # optional, default is true
          

    - name: Test
      run: go test -v ./...
